### PR TITLE
ReaRack modules moved to single package.

### PR DESCRIPTION
**Pull request by the-wasters-of-time**
Please review and merge if OK.

### CODE REVIEW

**Comment by cfillion** [comment]
It works, thanks! Note that with this way of packaging, there is only one visible changelog for the whole bundle. You can keep the version/author/changelog in the other files, but they are not used. (Only the ones in `Synth/TimeWaster_ReaRack Modular Synth.jsfx` are.)

Also note that before the new package can be installed, the old ones will have to be uninstalled first (ReaPack v1.1rcs have a feature for [this purpose](https://i.imgur.com/gZ9uqmY.png)).

If you whish, you can try it out first and see if you like that before I merge by importing this repo URL into ReaPack: https://raw.githubusercontent.com/ReaTeam/JSFX/the-wasters-of-time-master/index.xml.

(To go back to the public repository after testing, import https://github.com/ReaTeam/JSFX/raw/master/index.xml)

**Comment by the-wasters-of-time** [comment]
Hi Christian,

The package looks good, but I cant see anywhere an link to or mention of
the manual. I looked under both package contents and package history. The
package history mentions the changelog, but not he manual.

Regards,

Mal.

**Comment by the-wasters-of-time** [comment]
I'm beginning to think that JS effects need to have a 'help' button or some
way to put a clickable url in the graphics (I can't see any way of doing
that in the JS code).

**Comment by cfillion** [comment]
> I cant see anywhere an link to or mention of the manual. I looked under both package contents and package history. 

It's a new feature coming in ReaPack v1.1. Contents and history are merged in a single window with an additional About panel. It's currently in pre-release: https://github.com/cfillion/reapack/releases.

https://i.imgur.com/nd4Tctk.png

**Comment by the-wasters-of-time** [comment]
That will be good. I'm happy to use the package method.

Regards,

Mal.

**Comment by mschnell1** [comment]
@the-wasters-of-time : "I'm beginning to think that JS effects need to have a 'help' button or some way to put a clickable url in the graphics"

I already posted this in the "Feature Request" Forum. Yopu mioght want to add a "+1".

-Michael

**Comment by the-wasters-of-time** [comment]
@mshnell1, I added to your feature request.

Cheers,

Mal.

**Pull request merged**
