### PR TITLE
Create mschnell_delay_modulator.jsfx

### PR DESCRIPTION
**Pull request by mschnell1**
I hope I got the directory and the description correct this time....
-Michael

### CODE REVIEW

**Comment by mschnell1** [comment]
Hmm....
I think I created this in "Utility". Maybe "Modulation" would be more appropriate. But I don't know how to move it. 

-Michael

**Comment by cfillion** [comment]
The metadata is perfect. 😺 

You can move the file like this (at 0:14 I'm pressing Backspace as if to erase the slash):

gif

**Comment by mschnell1** [comment]
Any problems while this does not get processed ?

**Comment by mschnell1** [comment]
Did the renaming seemingly correctly (after a log digging for finding the "edit" option...) 

Do I need to do a new pull request ? Seems not possible.

-Michael

**Pull request merged**
