### PR TITLE
Release MIDI convert to CC v5.1

### PR DESCRIPTION
**Pull request by mschnell1**
Enhanced pass-through functionality

### CODE REVIEW

**Comment by mschnell1** [comment]
There were two false lines at the end due to the previous upload process.
-Michael

**Comment by colonel-blimp** [comment]
@mschnell1 That's not the only problem with 5.1; _all_ pass-through functionality is broken because slider10's values haven't been updated to deal with the new values. I don't think the _enhanced_ pass-through logic was implemented, either.   

I fixed what I could in #163, but I wasn't sure what you intended for the new modes.

**Comment by mschnell1** [comment]
I'll re-check
-Michael

**Comment by mschnell1** [comment]
see v5.2

**Pull request closed without merging**
