### PR TITLE
Utility/mschnell_Dual Time adjustment.jsfx

### PR DESCRIPTION
**Pull request by mschnell1**
New JSFX for Reapack, 

I hope I got the formating correct.

-Michael

### CODE REVIEW

**Comment by mschnell1** [comment]
Hmm. I suppose I forgot to add the ".jsfx" extension to the file name :(

**Comment by cfillion** [comment]
The file must also be put in a category (folder). `Utility` seems like a good choice?

Also there cannot be empty lines between the start of the file and the end of the reapack-index metadata header (except within an indented block for a tag value).


```
desc: Dual Time adjustment +/- Delay
tags: stereo delay
author: Michael Schnell (mschnell@bschnell.de)
version: 1.0
changelog: initial release
donation: United Nations Foundation http://www.unfoundation.org/
about:
  ## Description

  Apply a positive or negative delay to up tp two channel in a track
  modes: 

   - Stereo: All Sliders ar coupled
   - Dual: Two channels with two coupled sliders each 

  ## Acknowlages: 

  Based on "Channel Time Delayer [LOSER]" by Michael Gruhn, 2007

// (C) 2007, Michael Gruhn, 2017, Michael Schnell

// NO WARRANTY IS GRANTED. THIS PLUG-IN IS PROVIDED ON AN "AS IS" BASIS, WITHOUT
// WARRANTY OF ANY KIND. NO LIABILITY IS GRANTED, INCLUDING, BUT NOT LIMITED TO,
// ANY DIRECT OR INDIRECT,  SPECIAL,  INCIDENTAL OR CONSEQUENTIAL DAMAGE ARISING
// OUT OF  THE  USE  OR INABILITY  TO  USE  THIS PLUG-IN,  COMPUTER FAILTURE  OF
// MALFUNCTION INCLUDED.  THE USE OF THE SOURCE CODE,  EITHER  PARTIALLY  OR  IN
// TOTAL, IS ONLY GRANTED,  IF USED IN THE SENSE OF THE AUTHOR'S INTENTION,  AND
// USED WITH ACKNOWLEDGEMENT OF THE AUTHOR. FURTHERMORE IS THIS PLUG-IN A  THIRD
// PARTY CONTRIBUTION,  EVEN IF INCLUDED IN REAPER(TM),  COCKOS INCORPORATED  OR
// ITS AFFILIATES HAVE NOTHING TO DO WITH IT.  LAST BUT NOT LEAST, BY USING THIS
// PLUG-IN YOU RELINQUISH YOUR CLAIM TO SUE IT'S AUTHOR, AS WELL AS THE CLAIM TO
// ENTRUST SOMEBODY ELSE WITH DOING SO.

slider1:0<-100,100,0.01>Delay L (ms)
rest of the code...
```

**Comment by mschnell1** [comment]
Hopefully better now....

**Comment by cfillion** [comment]
The file was still at the root and the second desc (//desc:Channel Time Delayer [LOSER]) was overwriting the first one. I've updated it, it's good to merge now. :+1:

**Comment by mschnell1** [comment]
Sorry for my silliness :) 

Obviously I did it wrong (changing the title) and in fact I still have no idea how to "move the file in a category (folder)" and how to change it's name. (I already stopped contributing to another great project because I was not able to handle github: here I (mschnell without the "1" for that issues) would have needed to do a fork that supposedly would have allowed others to merge  current versions of the files others contribute in the "main" branch with files handled separately by a sub-group.) 

Seemingly, silly me also was not able to get the header format correct. (With the said other project I also stopped trying to improve the documentation for the multiple parts provided there, because there were no tools I would have been able to handle that allowed to preview the correctness of modifications before uploading. ) 

Thanks for fixing my errors !
-Michael

**Comment by cfillion** [comment]
You can rename files by clicking on the edit button (Pen icon in the "Files changed" tab) and type the new name and path in the filename edit field at the top.

Or you can do it locally with your favorite file explorer application.

As for header syntax and previewing: I think there's many things that can be improved in reapack-index to make sharing files easier.

Can I merge this PR as-is or will you make a new one (I can't merge the PR if it's closed, I must reopen it first)?

**Comment by mschnell1** [comment]
I seem always to close the projects when I want to upload a comment. There are only knobs to "close" and to "comment" (which I seemingly misunderstand to mean "do a new comment" but might mean "upload the comment you just wrote"). 

IMHO "pre"-viewing would be best achieved by just providing a means to view the "about" information of a file that is not in the database. Regarding JSFX a kind of "help" button ion the rim the tracks' FX chain window would be perfect (no idea if an extension is able to provide such, and no idea how something like that can be provided for the other file types ReaPack manages., 

Anyway: Thanks for your great work !

And yes: pleas re-open and merge, it possible. 

Thanks again,
-Michael

**Comment by mschnell1** [comment]
BTW.: It's slightly frustrating that I always like bashing others for not doing decent documentation for the otherwise great open source contributions they provide, and desperately fail when trying to do this myself. :( 

-Michael

**Pull request merged**
