### PR TITLE
TimeWaster's ReaRack Modules

### PR DESCRIPTION
**Pull request by the-wasters-of-time**
Please review and add these files if appropriate. I would have put them in a sub directory if I could have worked out how to create one.

### CODE REVIEW

**Comment by cfillion** [comment]
Seems all good! You can move the files to a subdirectory (I suppose you have "ReaRack" in mind?) by editing the files (one per one) using the GitHub web interface: https://github.com/blog/1436-moving-and-renaming-files-on-github.

Tell me when it's done and ready to be released.

**Comment by the-wasters-of-time** [comment]
Files now moved to sub directory ReaRack_ModularSynth.

**Comment by cfillion** [comment]
Thanks! It's released. I missed two things when I reviewed this yesterday:

1. Filenames should use spaces instead of underscore after the username like this: `ReaRack Modular Synth/TimeWaster_ReaRack XYZ.jsfx` (this is documented in the README)
2. Key Follower, LFO and Poly Splitter didn't have author information.

I fixed both and I'll be more careful next time.

**Comment by mschnell1** [comment]
IMHO it's not a good idea to extend the "category" "Synth" by "/ReaRack Modular Synth". 

I don't know how, but there should be a more decent way to create a naming bracket for parts of a combi of multiple scripts (I will need the same soon). 

Thanks for listening, 
-Michael

**Comment by mschnell1** [comment]
IMHO a more detailed "About" section on what the plugin is supposed to do and how it is intended to be used, especially in combination with the other "ReaRack" components would be [b]veŕy[/b] appropriate.

-Michael

**Comment by the-wasters-of-time** [comment]
@cfillion, Thanks for adding the files and making the changes required.

@mschnell1, I will update the "about" section of the files with a link to the user manual (when I have a moment spare). There is too much info, I think, to just put it all in the "about" section.

**Comment by mschnell1** [comment]
Yep I see. 

Where are you going to host the user manual ? 

Thanks,
-Michael

**Comment by cfillion** [comment]
> IMHO it's not a good idea to extend the "category" "Synth" by "/ReaRack Modular Synth".

I agree it's not the prettiest thing. Another way would be to be to bundle all the ReaRack FX in a single "ReaRack Modular Synth" entry in ReaPack. But then we'd loose the ability to install/update them individually of course.

**Comment by the-wasters-of-time** [comment]
Michael,

I was thinking of putting the manual in the 'misc' section of the REAPER
stash.

Cheers,
Mal.

**Comment by mschnell1** [comment]
"I agree it's not the prettiest thing. Another way would be to be to bundle all the ReaRack FX in a single "ReaRack Modular Synth" entry in ReaPack. But then we'd loose the ability to install/update them individually of course."

IMHO no problem at all. Installing them together is just a matter of seconds. As long as they can loaded separately in a Reaper project (which of course is given) I would recommend this. 

-Michael

**Comment by mschnell1** [comment]
What is "the REAPER stash" ? Who can use it, what are the terms ? 
-Michael

**Comment by the-wasters-of-time** [comment]
The stash - http://stash.reaper.fm/index.php

You just have to register.

**Comment by the-wasters-of-time** [comment]
@ Christian,

Is there a way to update my fork of the master to reflect the changes you
made to my files, or do I just delete my fork and create a new one?

Mal.

**Comment by cfillion** [comment]
GitHub's web interface is quite limited in this area. I believe the only clean way update a fork using it is to delete/recreate it.

I see you have a single manual for all FXs. I reiterate my proposal of making a single package for all ReaRack JSFX files. Or do you prefer to keep them separately installable?

**Comment by the-wasters-of-time** [comment]
By single package, do you mean a Zip file? Otherwise how do I package it up?

**Comment by cfillion** [comment]
Every package may include more than one file. Like this: https://i.imgur.com/xgeG3n6.png.

Here's how to create it:

1. Replace the header of each individual files in the "ReaRack Modular Synth" directory:

  ```yaml
  desc: ReaRack - XYZ
  noindex: true
  ```
  NoIndex tells reapack-index to skip that file and not make a package for it alone.
2. Create `/Synth/TimeWaster_ReaRack Modular Synth.jsfx`. It's a "metapackage": there is no JS code in this file, just a header to describe the contents. It will install all .jsfx files in the ReaRack Modular Synth subdirectory (but not itself).

    ```yaml
    desc: ReaRack Modular Synth
    author: Malcolm Smith
    version: 1.1
    changelog:
      cumulative list of changes in this release
    about:
      # ReaRack Modular Synth
      Description/list of the contents etc...
      ## User Guide
      Link to the user guide here...
    provides: ReaRack Modular Synth/*.jsfx
    metapackage: true
   ```

**Comment by mschnell1** [comment]
Distribution and installation looks great now !
Thanks,
-Michael
@the-wasters-of-time: I'll post some technical comments in the Reaper Forum.
-Michael

**Pull request merged**
