### PR TITLE
Release Loudener v1.0

### PR DESCRIPTION
**Pull request by samu4199**

### CODE REVIEW

**Comment by cfillion** [comment]
The image files should be uploaded to this repository to ensure long lasting availability. ("Upload local file" button on reapack.com/upload)

**Comment by samu4199** [comment]
What is the file size limit? Uploading from the website throws an error (saying it's too large). Are there any alternatives?
Thanks.

**Comment by cfillion** [comment]
I've increased the upload size limit to 10 MB.

**Comment by samu4199** [comment]
I've uploaded the files to this repository and updated the jsfx. Thank you.

**Pull request merged**
