### PR TITLE
Create mschnell_Midi Trigger CC.jsfx

### PR DESCRIPTION
**Pull request by mschnell1**
Again: Hopefully OK ?!?!?!?
-Michael

### CODE REVIEW

**Comment by cfillion** [comment]
There's a small typo in the documentation: "cahannel". 😺

**Comment by mschnell1** [comment]
Sorry. 
Again I am not able top edit the file. 

There seems to be no link from here how to find it. And if I anyhow do find it the "edit" Button is deactivated due to "you need to be on the branch to edit the file". 

This github thing really is not for me ;) 

-Michael

**Comment by mschnell1** [comment]
fixed the typo
-Michael

**Comment by mschnell1** [comment]
Wrong directory. 
I seem to create a pull request to change this. 
Again searching how to do that....
-Michael

**Pull request merged**
