### PR TITLE
Release Midi Fade X v2.2

### PR DESCRIPTION
**Pull request by mschnell1**
Fix initialization problems

### CODE REVIEW

**Comment by mschnell1** [comment]
Worked. 
But why have the previous versions remmoved from the server ?
Thanks
-Michael

**Comment by cfillion** [comment]
Side effect from renaming to uppercase MIDI. I've re-added the previous versions to the index.

**Comment by mschnell1** [comment]
Did I do this ?  
Thanks, anyway !
-Michael

**Comment by cfillion** [comment]
I did in e760736b3543406d4dfa22043d34a6b047ee1da4. I should have noticed that back when it was first released instead, but missed it.

**Comment by mschnell1** [comment]
Thanks again !
-Michael

**Pull request merged**
