### PR TITLE
Create mschnell_Midi CC Table.jsfx

### PR DESCRIPTION
**Pull request by mschnell1**
Hopefully OK....

### CODE REVIEW

**Comment by mschnell1** [comment]
Error message:

"1) Utility/mschnell_Midi CC Table.jsfx failed:
  missing tag 'version'
Finished checks for 60 packages with 1 failure"

in the file: 

"author: Michael Schnell (mschnell@bschnell.de)
version: 1.0
changelog: initial release"

I don't understand.
-Michael

**Comment by cfillion** [comment]
Header parsing stops at the first empty line. In this case it only sees `Author: Michael Schnell, `.

**Comment by mschnell1** [comment]
Retrying ....

**Comment by cfillion** [comment]
Mhh I just noticed this, shouldn't these JSFX go in the MIDI category instead of Utility?

**Comment by mschnell1** [comment]
In fact, I did these Plugins to work together for a dedicated purpose: using Reaper as a tool for live playing. So, no, IMHO, plain "Midi" would not be a better place than "Utility". 

On the long run, I suppose I will do some more stuff for this purpose: JSFXes, Scripts, project/track templates, documentation, and maybe even VSTs or Reaper C++ extension.  Others might follow that target, as well.

Hence a dedicated category might be viable. But anyway this is a kind of "Utility".

Is it possible to install a common category, and do common multi-packages, that hold files in subdirectories of multiple types (such as Effects/Scripts/...)

-Michael

**Comment by cfillion** [comment]
OK. My point of view is if a plugin's main feature is processing or generating MIDI (live or not) it should be categorized as such. But there are not formal rules for categorization at the moment and editing the category after the fact is non ideal (hopefully that will all change with the addition of a `@category` tag in the future).

> Is it possible to install a common category, and do common multi-packages, that hold files in subdirectories of multiple types (such as Effects/Scripts/...)

Yes! A single package is not limited to containing a single type of resource. Any package can contain any types ReaPack supports: scripts, effects, track templates, etc.

Doing so of course removes the ability for the user to search for and install each component individually. They're either all installed or none are. This can be good or bad depending on how you want your tools to be used. 😄

**Comment by mschnell1** [comment]
For somebody searching for something, the category is supposed to help finding an appropriate tool. may same be based on whatever technology. For a decent distinction between "Midi" and "audio" (and - say - "OSC"), a keyword "technology:" instead of "category:"  might sometimes be helpful. 

With a category "Midi" everybody thinks that music events are handled. With these plugins Midi is (ab-)used as a stream of configuration data, with no decent "musical" purpose. 

Hence category "Midi" is not appropriate. 

-Michael

**Comment by mschnell1** [comment]
In the Forum thread I already pointed out that it IMHO is a shortcoming, that the ReaPack browser does not find the single plugins that emerge from a package (y their names. Very obviously undesirable with the ReaRack package.

**Pull request merged**
